folder structure created
octoposprime/op-design pull request #4
Opened 2024-03-02 15:43 UTC by aleyna0f

folder structure created

2024-03-02 15:48 UTC, nurbeyzaoztrk approved these changes, later dismissed

2024-03-04 12:41 UTC, husamettinarabaci commented
Why the Pr was closed?

2024-03-04 12:42 UTC, husamettinarabaci requested changes
Please add resolution info in the file name or sub-folder name.

2024-03-08 17:32 UTC, nurbeyzaoztrk approved these changes

2024-03-10 02:55 UTC, husamettinarabaci approved these changes
Good work

2024-03-12 13:07 UTC, merged